### ISSUE TITLE
API key in the readme

### ISSUE THREAD

**Issue by ghassanmas** [FACK1/FoodRecipes#36]
You shouldn't share your API key or make it public, the point why you have created the .env file and one main benefit of sending APIrequests from the back-end is to hide the API key. 

Instead of adding it in the instruction to use the add, you should have said go to https://www.food2fork.com/ and generate an API key...

Please change the readme instruction to use the app accordingly.

**Comment by fdo2** [comment]
:scream:

**Comment by ghassanmas** [comment]
also relates #44

**Comment by ghassanmas** [comment]
Good Job

**Comment by mattlub** [comment]
I assume it is not such a problem with this API key, however, if you do upload a more sensitive key, it is not enough to just remove it, because the history still exists on Github and is easy to find!
